// <auto-generated />
namespace OneTrip3G.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class EditPlaceTable : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206081058349_EditPlaceTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy+X+Zu6WN37fCxtx6cEqi3y5qP0uCwyQuh1Xp6/J3Y7D4HdR7Zf6pnBXr+5XuXc+2cfvSypf78JNfq98uvgA/roZV2t8rq9fpWf64tns4/Su+F7d7sv2te8d9A3/bZs7+19lL5Yl2U2KemD86xs8o/S1aePXrdVnX+eL/M6a/PZy6xt83qJd3PGXWnwaPXp7cjw8O7OHshwN1suqzZraaZ7iHfQxL8G0ddtTUzzUfqseJfPnufLi3Zukf0ie2c+2SPO+WpZEIvRO229ziNj29zp6fKiLJr51+h7/4P7pnm7qupZ8012LH9v7vdp3kyJ62VO3qvr3Z0P7fsni1lePSvK96X23jfT8+viB7bnnjDcBsoX2ernBHvq9z1xf3zXaZ2NuuirJq9/pIp+7lXRy6xpoA/es2NQ8X06vjVfvM7bFgj8iDU+kDXufzBrPC2aVZldf42+N2ue23X+tc0F/fqhnf9kVq7fd8ybu31fTUn+ZJsVxHFGE8NTxIf5u7YjG/ICyY3v5ZF5d+DFoRyL+9cdevd1KObY26ywb3pZpTf2vhHsKBHscO13j++K46wfPL474GE/Jhu1QpfuTf0kfS3u9sn26/f3pRcC4+60ibjUFlvbEymI7CLvfEtdE6bPirppn2ZtNsnAMSezRa/ZbSbXdBXMcVcnOqKb5vhdXhmMOpQvOrAcHZ/R0Bak6XiUOkZCKBpO6Juvp1mZ1RFVe1KV68VySF1velu0kP++fHJ7CIHT7QMKvrg9POdI+8Dcp7eHFOg6H1jwxe3hee6uD837+D1hiRPYgyUf3x6WdWN9SPbD94LTx8h+2Ifz+G6Hlbty46libdlxI7pieCshFU36zcho311mYDeJaPy1/7dKqPNFfSju0//XzKw1c9/M5EZ9XoZ30/wOvvn/1ikOfMpA1flfvAe8b1p1Zuz5BapOPvohM1/PM+o2sb3rJ/Zv6xmpV/KF7y7xuLsJyZ6bIk0+Sok4l6ToyUV5fd20+WKMBuPXv6g8KQsar2vwRbYszvOmfVO9zZfs/x98/WSmjY+aZlb+vzKjWWDsN0aF7xl0COtLB8vLrJ7Os7oX7L8nzEiiMQp6//1Bd/OIt4B7m5RTJO6LQuak4PuB7mUBB6j83jj3knzMH+8Ho5Pi+6ZQ62TwbkTs1nman5v83f9nBK+bVovCjeabvtZs/JxlzX5uJuT++09IJJl1Gxm7HexhnbW1yN7deW+AQf5pENT7Sm83p9TPToRIWe8kMLaDeSVxGj77aDapCHVB0eSiOsPtQpbcUg+wfByDq0mqG8DalFMPsv0mBtwlsWK0vUWqqu94Pb7rrxc/JoYpLhwIrB4v8yn4xwE1bc6W55VhD8LMx8g06er8vM1mNKXHdVucZ9OWvqZJaHi8zFnkFywm+exs+eW6Xa3b46bJF5Py2h/v47ub++d8XIjz4y9ZAjxP8+sPgdAsaAj5l8sn66KcWbyfdaRnAwhwt+okwoqSuATu4tpCelEtu8IzAEjJ9zRf5UtotDf5gjRJmzdfLl9nl/kwbjfTMKTY46dFdlFnC5+C8onh54x69rqgDvw3XH/0J7HrbPHu6P8JAAD//zrMJoYhIQAA"; }
        }
    }
}
