// <auto-generated />
namespace OneTrip3G.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitDatabase : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206070507208_InitDatabase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/soy+X+Zu6WN37fMxtx6cEqb3+KD0ui4yweZ2X5++J2s5DoPaR7ZS6FaBvrlc5d/3ZRy9L6txvQo1+r/w6+IA+ellXq7xur1/l5/ri2eyj9G743t3ui/Y17x30Tb8t23t7H6Uv1mWZTUr64Dwrm/yjdPXpo9dtVeef58u8ztp89jJr27xe4t1cCcI0eLT69HZkeHh3Zw9kuJstl1WbtTTNPcQ7aOJfg+jrtiaO+Sh9VrzLZ8/z5UU7t8h+kb0zn+wR23y1LIi/6J22XueRsW3u9HR5URbN/Gv0vf/BfdO8XVX1rPkmO5a/N/f7NG+mxPIyJ+/V9e7Oh/b9k8Usr54V5ftSe++b6fl18YP37Zl+/cCev8hWPycjpn5/CON9fNdpt40676smr3+k8n7uVd7LrGmgd96zY1DxfTq+NV+8ztsWCPyINT6QNe5/MGs8LZpVmV1/jb43a6vbdf61zdJmlXWrzn8yK9fvO+ZvVlOS09pmBXGc0d5wR/Fh/q7tyIa8QHLje5PkRjjw4riOxc3sDr37OhRz7G1W2De9rNIbe98IdpQIdrj2u8d3xTvXDx7fHXDjH5NdW6FL96Z+kr4Wn/5k+/X7++wLgXF32kRcd4ut7YkURHaRd76lrgnTZ0XdtE+zNptk4JiT2aLX7DaTa7oK5rirEx3RTXP8Lq/EQxtlig4gR8RnNK4FqTkeog6QsInGLPrm62lWZnVEz55U5XqxHNLVm94WFeS/L5/cHkLg2fuAgi9uD8956z4w9+ntIQWKzgcWfHF7eJ5P7UPzPn5PWOI19mDJx7eHZf1eH5L98L3g9DGyH/bhPL7bYeWu0Hh6WFt2fIiuDN5KQkWNfgMC2neUGdJN8hl/7f+t4um8UB+K+/T/NdNqDdw3MLNRV5eB3TS5g2/+v3V+A1cyUHL+F+8B75tWmhk7fIGSk49+yJzXc4i6TWzv+on92zpE6ox84XtJPO5usrPnnUiTj1IiziWpePJMXl83bb4Yo8H49S8qT8qCxusafJEti/O8ad9Ub/Mlu/0HXz9XasOippmV/69MmBYY+43B4HvGGsL60sHyMqun86zuxfjvCTOSx4yC3n9/0N005SDc98tORcK9KGTOOb4f6F6ScYDKXw+wn1MzgLcW2bs77wutkxf8ppDspP3eA8Vbp2x+blJ5/58Rxm6GLQo3mnr6WrPxc5ZA+7mZkPvvPyGRvNZtpO12sIf1WE/kbgUwSEV9Y9LbTS/1ExUhUtZjCQzwYIpJHInPPppNKkJdUDRpqc5wu5AlzdQDLB/H4Gq+6gawNvvUg2y/iQF3+awYbW+Rteo7Y4/v+uvTj4lhigsHAqvVy3wK/nFATZuz5Xll2IMw8zEyTbraP2+zGU3pcd0W59m0pa9pEhoeL3MW+QqLST47W365blfr9rhp8sWkvPbH+/ju5v45NRfi/PjLVUt/ed7n1x8CoVnQEPIvl0/WRTmzeD+L6MgBEOBu1UmEFeVzCdzFtYX0olreEpCS72m+ypfQaG/yBWmSNm++XL7OLvNh3G6m4ZesM6wT/7TILups4VNQPjH8nFHPXhfUgf+G64/+JHadLd4d/T8BAAD//xATiveRIQAA"; }
        }
    }
}
