// <auto-generated />
namespace Web.Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitDatabase : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206040717588_InitDatabase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so+/mk7G0Gp8SkLbIm4/S47LICJXXeXn+nnjtPAReH9keqU8Ge/3mepVzv5999FWT134LavN75dfBB/TRy7pa5XV7/So/1/fOZh+ld8P37nZftK9576Br+m3Z3tv7KH2xLstsUtIH51nZ5B+lq08fvW6rOv88X+Z11uazl1nb5vUS7+aMupLg0erT21Hh4d2dPVDhbrZcVm3W0hT3EO+giX8Noq/bmrjlo/RZ8S6fPc+XF+3cIvtF9s58skcs89WyIN6id9p6nUfGtrnTl1nTXFW1pdAtOwYV36fjx3cdB2zki5clceSPGOPnnjFOlxdl0cx/Tvr+yWKWV8+K8n17pl83dC1/36Ln18UPbM89xrgNlC+y1c8J9tTve+K+WS7JhrRZQZxv4MNG4MP8XduRUXnhdd56+p2MiIMulmTMer87jO7LrARib4t2iI7A4uoM3V2xdMYi3h0wiY+JbCuaIM9E6ifpa7GPJ9uv398ELgTG3WkTsYQWW9sTaZnsIu98S10Tps+KummfZm02ycAyJ7NFr9ltZsZ05U9QV686ipvW+F3eiHgJ474ZZzD68jMa0oLUJI9Ox0aIxKy/vvh6mpVZHVHTJ1W5XiyHVP2mt0WD+e/LJ7eH4GykD8V92of0+G6HAl06e2KnLTumqztrt5pTlZsPndSIDWY4N83qwHv/b53WwML5gIIvbg/Ps1o+NO/j94QlurwHSz6+PSxrjXxI9sP3gtPHyH74QxaCntrvNrG9W/XfUfOPVeUGtoDH3g2PejpYmnyUEoEuaUZI/76+btp8MUaD8etfVJ6UBY3XNfgiWxbnedO+qd7mCPXIRHz9AMt6kE0zK//fGGUVGPqNbvN7+oQijdLB8jKrp/Os7rmd7wmzG/xE4Ubjgtv7UD/3sc3/Z6YjEnJ8U6B7EYUBvLXI3t15Xz+7FyUwid8PRidG+CB8On7/jdi8n9ffd0FDZKyW9pXOkOcvqvOzj2aTitAVBDVWuE1QMBwTxACbOOJrxgt9A/H4rp9le/w0b4oLBwI5t2U+RUjvgJo2Z8vzykwbDcrHyDTpzmreZjMi+XHdFufZtKWvaTQNh5I/mZVrSMxiks/Oll+u29W6PW6afDEpr/3xPr67uX8OikKcH3+5wl+eRfz6QyA0CxpC/uXyybooZxbvZxEtOgAC3Kd6i7CiUJrAXVxbSC+q5S0BKfme5qt8Ca33Jl+sSgLWfLl8nV3mw7jdTMOQYo+fFtlFnS18CsonisnrjHr2uqAO/Ddcf/QnsSuleI/+nwAAAP//qL0cRlcWAAA="; }
        }
    }
}
